services:
  - type: web
    name: shopsphere-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node backend/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false

  - type: web
    name: shopsphere-frontend
    env: node
    plan: free
    buildCommand: "npm install --prefix frontend && npm run build --prefix frontend"
    startCommand: "serve -s frontend/build"
    envVars:
      - key: NODE_ENV
        value: production
